apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: budget-guard-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: budget-guard-manager-role
subjects:
- kind: ServiceAccount
  name: budget-guard-controller-manager
  namespace: prophet-operators

