apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8sgpt-extension.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8sgpt-extension.labels" . | nindent 4 }}
    catalog.cattle.io/ui-extensions-version: ">=3.0.0"
data:
  plugin.json: |
    {
      "name": "{{ .Values.plugin.name }}",
      "version": "{{ .Values.plugin.version }}",
      "description": "Rancher UI Extension for K8sGPT Diagnostics",
      "enabled": {{ .Values.plugin.enabled }}
    }

