apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

patches:
  - path: nodepool-patch.yaml
    target:
      kind: NodePool
  - path: nodeclass-patch.yaml
    target:
      kind: AKSNodeClass

commonLabels:
  environment: production

